import React from 'react';
import { Link } from 'react-router-dom';
import Icon from 'components/AppIcon';

const PrivacyPolicy = () => {
    const lastUpdated = "April 13, 2026";

    return (
        <div className="min-h-screen bg-cream/30 pt-24 pb-16">
            <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
                {/* Header */}
                <div className="mb-12 text-center">
                    <div className="inline-flex items-center space-x-3 mb-6">
                        <div className="w-12 h-12 bg-gradient-to-br from-primary to-secondary rounded-full flex items-center justify-center">
                            <Icon name="Shield" size={24} className="text-white" />
                        </div>
                    </div>
                    <h1 className="text-4xl font-heading font-bold text-text-primary mb-4">
                        Privacy Policy for Eva Smart Ring
                    </h1>
                    <p className="text-text-secondary font-body">
                        Last Updated: {lastUpdated}
                    </p>
                </div>

                {/* Content */}
                <div className="bg-white rounded-brand shadow-gentle p-8 lg:p-12 prose prose-slate max-w-none">
                    <p className="lead text-lg text-text-secondary mb-8">
                        At Eva Smart Ring ("we," "our," or "us"), we are committed to protecting your privacy. This Privacy Policy explains how we collect, use, and safeguard your information when you visit our website, use the Eva Smart Ring, or interact with our mobile application.
                    </p>

                    <section className="mb-10">
                        <h2 className="text-2xl font-heading font-semibold text-text-primary mb-4 flex items-center">
                            <span className="w-8 h-8 bg-primary/10 rounded-full flex items-center justify-center mr-3 text-primary text-sm">1</span>
                            Information We Collect
                        </h2>
                        <p className="text-text-secondary mb-4">
                            We collect information that you provide directly to us, as well as data generated by your use of the smart ring.
                        </p>
                        <ul className="space-y-3 text-text-secondary">
                            <li className="flex items-start">
                                <Icon name="Check" size={18} className="text-success mt-1 mr-3 flex-shrink-0" />
                                <span><strong>Personal Information:</strong> Name, email address, shipping address, and payment information when you purchase a ring or create an account.</span>
                            </li>
                            <li className="flex items-start">
                                <Icon name="Check" size={18} className="text-success mt-1 mr-3 flex-shrink-0" />
                                <span><strong>Health & Wellness Data:</strong> Because the Eva Smart Ring is a wearable health tracker, we collect biometric data such as heart rate, sleep patterns, body temperature, blood oxygen levels (SpO2), and activity metrics (steps, calories).</span>
                            </li>
                            <li className="flex items-start">
                                <Icon name="Check" size={18} className="text-success mt-1 mr-3 flex-shrink-0" />
                                <span><strong>Device Information:</strong> Technical data such as your IP address, browser type, operating system, and the unique ID of your Eva Smart Ring.</span>
                            </li>
                            <li className="flex items-start">
                                <Icon name="Check" size={18} className="text-success mt-1 mr-3 flex-shrink-0" />
                                <span><strong>Cookies:</strong> We use cookies to improve your browsing experience and analyze website traffic.</span>
                            </li>
                        </ul>
                    </section>

                    <section className="mb-10">
                        <h2 className="text-2xl font-heading font-semibold text-text-primary mb-4 flex items-center">
                            <span className="w-8 h-8 bg-primary/10 rounded-full flex items-center justify-center mr-3 text-primary text-sm">2</span>
                            How We Use Your Information
                        </h2>
                        <p className="text-text-secondary mb-4">
                            We use the collected data for the following purposes:
                        </p>
                        <ul className="space-y-3 text-text-secondary">
                            <li className="flex items-start">
                                <Icon name="Activity" size={18} className="text-primary mt-1 mr-3 flex-shrink-0" />
                                <span><strong>To Provide Services:</strong> To display your health trends and insights within the app.</span>
                            </li>
                            <li className="flex items-start">
                                <Icon name="Activity" size={18} className="text-primary mt-1 mr-3 flex-shrink-0" />
                                <span><strong>Personalization:</strong> To offer tailored wellness recommendations based on your biometric data.</span>
                            </li>
                            <li className="flex items-start">
                                <Icon name="Activity" size={18} className="text-primary mt-1 mr-3 flex-shrink-0" />
                                <span><strong>Order Fulfillment:</strong> To process transactions and ship your Eva Smart Ring.</span>
                            </li>
                            <li className="flex items-start">
                                <Icon name="Activity" size={18} className="text-primary mt-1 mr-3 flex-shrink-0" />
                                <span><strong>Communication:</strong> To send updates, security alerts, and support messages.</span>
                            </li>
                            <li className="flex items-start">
                                <Icon name="Activity" size={18} className="text-primary mt-1 mr-3 flex-shrink-0" />
                                <span><strong>Improvement:</strong> To analyze how our users interact with the device to improve hardware and software performance.</span>
                            </li>
                        </ul>
                    </section>

                    <section className="mb-10">
                        <h2 className="text-2xl font-heading font-semibold text-text-primary mb-4 flex items-center">
                            <span className="w-8 h-8 bg-primary/10 rounded-full flex items-center justify-center mr-3 text-primary text-sm">3</span>
                            Data Sharing and Disclosure
                        </h2>
                        <p className="text-text-secondary mb-4">
                            We <strong>do not sell</strong> your personal health data to third parties. We may share information only in the following cases:
                        </p>
                        <ul className="space-y-3 text-text-secondary">
                            <li className="flex items-start">
                                <Icon name="Share2" size={18} className="text-secondary mt-1 mr-3 flex-shrink-0" />
                                <span><strong>Service Providers:</strong> With vendors who help us with website hosting, payment processing, or shipping.</span>
                            </li>
                            <li className="flex items-start">
                                <Icon name="Share2" size={18} className="text-secondary mt-1 mr-3 flex-shrink-0" />
                                <span><strong>Legal Requirements:</strong> If required by law, subpoena, or to protect the safety and rights of our users.</span>
                            </li>
                            <li className="flex items-start">
                                <Icon name="Share2" size={18} className="text-secondary mt-1 mr-3 flex-shrink-0" />
                                <span><strong>Anonymized Data:</strong> We may share aggregated, non-identifiable data for research or marketing purposes.</span>
                            </li>
                        </ul>
                    </section>

                    <section className="mb-10">
                        <h2 className="text-2xl font-heading font-semibold text-text-primary mb-4 flex items-center">
                            <span className="w-8 h-8 bg-primary/10 rounded-full flex items-center justify-center mr-3 text-primary text-sm">4</span>
                            Data Security
                        </h2>
                        <p className="text-text-secondary leading-relaxed">
                            We implement industry-standard security measures, including encryption (SSL/TLS), to protect your sensitive health data. However, no method of transmission over the internet is 100% secure, and we cannot guarantee absolute security.
                        </p>
                    </section>

                    <section className="mb-10">
                        <h2 className="text-2xl font-heading font-semibold text-text-primary mb-4 flex items-center">
                            <span className="w-8 h-8 bg-primary/10 rounded-full flex items-center justify-center mr-3 text-primary text-sm">5</span>
                            Your Rights
                        </h2>
                        <p className="text-text-secondary mb-4">
                            Depending on your location (such as the EU under GDPR or California under CCPA), you may have the right to:
                        </p>
                        <ul className="space-y-3 text-text-secondary">
                            <li className="flex items-start">
                                <Icon name="ChevronRight" size={18} className="text-primary mt-1 mr-3 flex-shrink-0" />
                                <span>Access the personal data we hold about you.</span>
                            </li>
                            <li className="flex items-start">
                                <Icon name="ChevronRight" size={18} className="text-primary mt-1 mr-3 flex-shrink-0" />
                                <span>Request the deletion of your account and health history.</span>
                            </li>
                            <li className="flex items-start">
                                <Icon name="ChevronRight" size={18} className="text-primary mt-1 mr-3 flex-shrink-0" />
                                <span>Opt-out of marketing communications.</span>
                            </li>
                            <li className="flex items-start">
                                <Icon name="ChevronRight" size={18} className="text-primary mt-1 mr-3 flex-shrink-0" />
                                <span>Correct inaccurate information.</span>
                            </li>
                        </ul>
                    </section>

                    <section className="mb-10">
                        <h2 className="text-2xl font-heading font-semibold text-text-primary mb-4 flex items-center">
                            <span className="w-8 h-8 bg-primary/10 rounded-full flex items-center justify-center mr-3 text-primary text-sm">6</span>
                            Children’s Privacy
                        </h2>
                        <p className="text-text-secondary leading-relaxed">
                            The Eva Smart Ring is not intended for use by individuals under the age of 13 (or 16 in certain jurisdictions). We do not knowingly collect personal data from children.
                        </p>
                    </section>

                    <section className="mb-10">
                        <h2 className="text-2xl font-heading font-semibold text-text-primary mb-4 flex items-center">
                            <span className="w-8 h-8 bg-primary/10 rounded-full flex items-center justify-center mr-3 text-primary text-sm">7</span>
                            Changes to This Policy
                        </h2>
                        <p className="text-text-secondary leading-relaxed">
                            We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new policy on this page and updating the "Last Updated" date.
                        </p>
                    </section>

                    <section className="mb-10">
                        <h2 className="text-2xl font-heading font-semibold text-text-primary mb-4 flex items-center">
                            <span className="w-8 h-8 bg-primary/10 rounded-full flex items-center justify-center mr-3 text-primary text-sm">8</span>
                            Contact Us
                        </h2>
                        <p className="text-text-secondary mb-4">
                            If you have questions about this Privacy Policy, please contact us at:
                        </p>
                        <div className="bg-surface p-6 rounded-organic border border-border">
                            <div className="flex items-center space-x-3 mb-2">
                                <Icon name="Mail" size={20} className="text-primary" />
                                <a href="mailto:mdoffice@dkgrouplabs.com" className="text-primary font-medium hover:underline">
                                    mdoffice@dkgrouplabs.com
                                </a>
                            </div>
                            <p className="text-sm text-text-secondary">
                                Our team is available to address any privacy-related concerns you may have.
                            </p>
                        </div>
                    </section>

                    {/* Vercel Note as requested in implementation notes */}
                    <div className="mt-12 pt-8 border-t border-border">
                        <p className="text-sm text-text-tertiary italic">
                            Note: This site is hosted on Vercel. Technical data (IP, location, browser) is processed by Vercel Analytics to improve site performance.
                        </p>
                    </div>
                </div>

                {/* Back to Home */}
                <div className="mt-12 text-center">
                    <Link
                        to="/"
                        className="inline-flex items-center space-x-2 text-text-secondary hover:text-primary transition-whisper"
                    >
                        <Icon name="ArrowLeft" size={20} />
                        <span className="font-medium">Back to Homepage</span>
                    </Link>
                </div>
            </div>
        </div>
    );
};

export default PrivacyPolicy;
